### PR TITLE
Implement xhr upload feature

### PR DESCRIPTION
**Pull request by cibernox**
Based on the work of @cowboyd.

Real world example already working with pretender and ember-cli-mirage: http://quick.as/jpw4i9rbr

### CODE REVIEW

**Comment by cibernox** [comment]
I'll revisit this later today to clean up the code and maybe add more tests

**Comment by cibernox** [comment]
@trek Please, check this out.

If this get's merged I'll make 2 cascade PRs to pretender and ember-cli-mirage to get this available to my current app.

**Comment by cibernox** [comment]
Any feedback to apply on this?

**Comment by trek** [comment]
Looks good to me!

**Comment by cibernox** [comment]
Great. Are you planning to bump the version number anytime soon?

**Comment by cibernox** [comment]
@trek ping on the version bump. I'll have some OSS time this weekend

**Pull request merged**
